### PR TITLE
Update GAN to new requirements

### PR DESCRIPTION
**Pull request by bolasim**

### CODE REVIEW

**Comment by squidarth** [comment]
could you please add this to the https://github.com/basetenlabs/truss-examples/blob/main/ci.yaml file?

**Review by squidarth — APPROVED** [review]
lgtm modulo adding to ci

**Comment by bolasim** [comment]
will do. just got to figure out the correct input to test with.

**Comment by bolasim** [comment]
@squidarth can you take another pass? I made some changes to the CI job to make this testable without making the config unreadable.

**Pull request merged**
