### PR TITLE
whisperx-truss

### PR DESCRIPTION
**Pull request by htrivedi99**
I'm trying to add this Truss for [whisperx](https://github.com/m-bain/whisperX) but I'm having issues loading the model. In the load function, immediately after the model gets downloaded I receive and error saying: "RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the mode". I tried changing python package versions, but keep getting the same error. Anyone have an idea on how to fix this?

### CODE REVIEW

**Comment by squidarth** [comment]
Hey @htrivedi99 that's weird, are you able to repro this when you run this line locally on your computer:

```
$ whisperx.load_model("large-v2", self.device, compute_type=self.compute_type)
```

**Comment by htrivedi99** [comment]
> Hey @htrivedi99 that's weird, are you able to repro this when you run this line locally on your computer:

I ran it using google colab and it works just fine. I've tried multiple versions of the python packages to see if there are issues with compatibility, but I keep getting the same error.

**Comment by htrivedi99** [comment]
> Hey @htrivedi99 that's weird, are you able to repro this when you run this line locally on your computer:
> 
> ```python
> >> whisperx.load_model("large-v2", self.device, compute_type=self.compute_type)
> ```

Hey, I just got it working. There was an issue inside the whisperx code base not downloading the model correctly. I downloaded it manually and it works correctly now :)

**Review by squidarth — COMMENTED** [review]
thoughts on torch version pinning? Happy to merge it after we make a decision on that!

**Comment by htrivedi99** [comment]
> thoughts on torch version pinning? Happy to merge it after we make a decision on that!

Good catch! Adding them now

**Comment by squidarth** [comment]
@htrivedi99 thanks! merging now

**Pull request merged**
